---
- name: provide default SSH config
  copy: src=ssh.conf dest=.ssh/config owner=zdun group=zdun
- name: install libraries
  apt: name={{ essential_libraries }} state=latest update_cache=yes
- name: add PPA for Git
  apt_repository: repo='ppa:git-core/ppa'
- name: install packages
  apt: name={{ essential_packages }} state=latest update_cache=yes
- name: update timezone
  copy: content='Europe/Paris' dest=/etc/timezone owner=root group=root mode=0644 backup=yes
  notify: update timezone
